import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import { getDatabase, ref, onValue, set, push, remove, get } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-database.js';
import { getStorage, ref as sRef, uploadBytesResumable, getDownloadURL } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-storage.js';
import { firebaseConfig, COLLECTION_ROOT } from './firebase-config.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app),storage=getStorage(app),root=COLLECTION_ROOT;
let products={},articles={},settings={};
const $=id=>document.getElementById(id);const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value)}catch(err){$('loginMsg').textContent='تعذر الدخول: '+friendly(err.code);$('loginMsg').classList.remove('hidden')}});$('logoutBtn').onclick=()=>signOut(auth);
onAuthStateChanged(auth,user=>{$('loginView').classList.toggle('hidden',!!user);$('dashboard').classList.toggle('hidden',!user);if(user)bindData()});
function friendly(c){return c?.includes('invalid-credential')?'راجع البريد وكلمة المرور.':c?.includes('too-many')?'محاولات كثيرة، جرب لاحقاً.':c||'خطأ غير معروف'}
document.querySelectorAll('.side-link[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.side-link[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$('tab-'+b.dataset.tab).classList.remove('hidden')});
function bindData(){onValue(ref(db,`${root}/products`),s=>{products=s.val()||{};$('statProducts').textContent=Object.keys(products).length;renderProducts()});onValue(ref(db,`${root}/articles`),s=>{articles=s.val()||{};$('statArticles').textContent=Object.keys(articles).length;renderArticles()});onValue(ref(db,`${root}/settings`),s=>{settings=s.val()||{};$('statPhone').textContent=settings.whatsapp||'-';$('sName').value=settings.shopName||'عسل القنيطرة';$('sWhatsapp').value=settings.whatsapp||'';$('sHero').value=settings.heroText||''})}
async function upload(file,folder,progressEl){if(!file)return null;const safe=`${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const task=uploadBytesResumable(sRef(storage,`${root}/${folder}/${safe}`),file);return new Promise((res,rej)=>task.on('state_changed',snap=>progressEl.style.width=Math.round(snap.bytesTransferred/snap.totalBytes*100)+'%',rej,async()=>res(await getDownloadURL(task.snapshot.ref))))}
$('productForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('productId').value||push(ref(db,`${root}/products`)).key;let image=products[id]?.image||'';const file=$('pImage').files[0];if(file)image=await upload(file,'products',$('pProgress'));await set(ref(db,`${root}/products/${id}`),{name:$('pName').value.trim(),weight:$('pWeight').value.trim(),price:Number($('pPrice').value),oldPrice:Number($('pOldPrice').value)||0,badge:$('pBadge').value.trim(),description:$('pDesc').value.trim(),image,active:true,updatedAt:Date.now()});resetProduct()});
$('articleForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('articleId').value||push(ref(db,`${root}/articles`)).key;let image=articles[id]?.image||'';const file=$('aImage').files[0];if(file)image=await upload(file,'articles',$('aProgress'));await set(ref(db,`${root}/articles/${id}`),{title:$('aTitle').value.trim(),excerpt:$('aExcerpt').value.trim(),content:$('aContent').value.trim(),image,active:true,createdAt:articles[id]?.createdAt||Date.now(),updatedAt:Date.now()});resetArticle()});
$('settingsForm').addEventListener('submit',async e=>{e.preventDefault();await set(ref(db,`${root}/settings`),{shopName:$('sName').value.trim(),whatsapp:$('sWhatsapp').value.replace(/\D/g,''),heroText:$('sHero').value.trim()});alert('تم حفظ الإعدادات')});
function renderProducts(){$('productsAdminList').innerHTML=Object.entries(products).map(([id,p])=>`<div class="admin-item"><img class="admin-thumb" src="${esc(p.image)}"><div><strong>${esc(p.name)}</strong><div>${Number(p.price||0)} درهم · ${esc(p.weight)}</div></div><div class="item-actions"><button class="btn btn-soft" data-edit-p="${id}">تعديل</button><button class="btn danger" data-del-p="${id}">حذف</button></div></div>`).join('')||'<div class="notice">لا توجد منتجات بعد.</div>';document.querySelectorAll('[data-edit-p]').forEach(b=>b.onclick=()=>editProduct(b.dataset.editP));document.querySelectorAll('[data-del-p]').forEach(b=>b.onclick=async()=>{if(confirm('حذف المنتج؟'))await remove(ref(db,`${root}/products/${b.dataset.delP}`))})}
function renderArticles(){$('articlesAdminList').innerHTML=Object.entries(articles).map(([id,a])=>`<div class="admin-item"><img class="admin-thumb" src="${esc(a.image)}"><div><strong>${esc(a.title)}</strong><div>${esc(a.excerpt).slice(0,80)}</div></div><div class="item-actions"><button class="btn btn-soft" data-edit-a="${id}">تعديل</button><button class="btn danger" data-del-a="${id}">حذف</button></div></div>`).join('')||'<div class="notice">لا توجد مقالات بعد.</div>';document.querySelectorAll('[data-edit-a]').forEach(b=>b.onclick=()=>editArticle(b.dataset.editA));document.querySelectorAll('[data-del-a]').forEach(b=>b.onclick=async()=>{if(confirm('حذف المقال؟'))await remove(ref(db,`${root}/articles/${b.dataset.delA}`))})}
function editProduct(id){const p=products[id];$('productId').value=id;$('pName').value=p.name||'';$('pWeight').value=p.weight||'';$('pPrice').value=p.price||'';$('pOldPrice').value=p.oldPrice||'';$('pBadge').value=p.badge||'';$('pDesc').value=p.description||'';window.scrollTo({top:0,behavior:'smooth'})}function resetProduct(){$('productForm').reset();$('productId').value='';$('pProgress').style.width='0'}$('pReset').onclick=resetProduct;
function editArticle(id){const a=articles[id];$('articleId').value=id;$('aTitle').value=a.title||'';$('aExcerpt').value=a.excerpt||'';$('aContent').value=a.content||'';window.scrollTo({top:0,behavior:'smooth'})}function resetArticle(){$('articleForm').reset();$('articleId').value='';$('aProgress').style.width='0'}$('aReset').onclick=resetArticle;
$('seedBtn').onclick=async()=>{if(!confirm('إضافة 3 منتجات ومقالين تجريبيين؟'))return;const pRef=ref(db,`${root}/products`),aRef=ref(db,`${root}/articles`);const [ps,as]=await Promise.all([get(pRef),get(aRef)]);if(!ps.exists())await set(pRef,{thyme:{name:'عسل الزعتر',price:120,oldPrice:140,weight:'500g',badge:'الأكثر طلباً',description:'عسل بنكهة قوية وقوام غني.',image:'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=900&q=80',active:true},flowers:{name:'عسل متعدد الأزهار',price:90,weight:'500g',badge:'اختيار يومي',description:'مذاق متوازن مناسب للاستعمال اليومي.',image:'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&w=900&q=80',active:true},premium:{name:'عسل حر',price:160,weight:'500g',badge:'مميز',description:'اختيار غني بالنكهة لمحبي العسل المميز.',image:'https://images.unsplash.com/photo-1471943311424-646960669fbc?auto=format&fit=crop&w=900&q=80',active:true}});if(!as.exists())await set(aRef,{choose:{title:'كيف تختار العسل المناسب؟',excerpt:'نقاط بسيطة تساعدك تختار العسل المناسب.',content:'شوف المصدر، المذاق، الوزن والاستعمال اللي باغيه. وخزن العسل بعيد على الحرارة والرطوبة.',image:'https://images.unsplash.com/photo-1587049352851-8d4e89133924?auto=format&fit=crop&w=900&q=80',active:true,createdAt:Date.now()},store:{title:'أفضل طريقة لحفظ العسل',excerpt:'حافظ على الجودة والقوام بهاد النصائح.',content:'خلي العسل فمرطبان مسدود مزيان وبعيد على الشمس. التبلور الطبيعي ما كيعنيش أن العسل فاسد.',image:'https://images.unsplash.com/photo-1499195333224-3ce974eecb47?auto=format&fit=crop&w=900&q=80',active:true,createdAt:Date.now()-1000}});alert('تمت إضافة المحتوى التجريبي')};
