import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import { getDatabase, ref, onValue } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-database.js';
import { firebaseConfig, COLLECTION_ROOT } from './firebase-config.js';
const app=initializeApp(firebaseConfig);const db=getDatabase(app);
const root=COLLECTION_ROOT;
let settings={shopName:'عسل القنيطرة',whatsapp:'212600000000',heroText:'عسل طبيعي مختار بعناية مع توصيل داخل القنيطرة والنواحي.'};
let articlesCache={};
const fallbackProducts=[
{id:'demo1',name:'عسل الزعتر',price:120,oldPrice:140,weight:'500g',badge:'الأكثر طلباً',description:'مذاق قوي ورائحة زكية، مناسب لمحبي العسل الطبيعي المركز.',image:'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=900&q=80'},
{id:'demo2',name:'عسل متعدد الأزهار',price:90,weight:'500g',badge:'اختيار يومي',description:'عسل متوازن المذاق للاستعمال اليومي مع الفطور والمشروبات.',image:'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&w=900&q=80'},
{id:'demo3',name:'عسل حر',price:160,weight:'500g',badge:'مميز',description:'اختيار مميز لمحبي العسل الغني بالنكهة والقوام.',image:'https://images.unsplash.com/photo-1471943311424-646960669fbc?auto=format&fit=crop&w=900&q=80'}];
const fallbackArticles=[
{id:'a1',title:'كيف تختار العسل المناسب؟',excerpt:'تعرف على أهم النقاط التي تساعدك تختار العسل حسب المذاق والاستعمال.',content:'اختيار العسل كيعتمد على المذاق، المصدر والاستعمال. قبل الشراء شوف وصف المنتج، الوزن، والثمن، وسول البائع على المصدر وطريقة الحفظ.\n\nخزن العسل فمكان جاف وبعيد على الحرارة المباشرة.',image:'https://images.unsplash.com/photo-1587049352851-8d4e89133924?auto=format&fit=crop&w=900&q=80',createdAt:Date.now()},
{id:'a2',title:'أفضل طريقة لحفظ العسل',excerpt:'نصائح بسيطة باش يبقى العسل عندك بنفس الجودة والقوام.',content:'خلي العسل فمرطبان مسدود مزيان، بعيد على الشمس والرطوبة. ما كاين حتى داعي تحطه فالثلاجة. التبلور الطبيعي ما كيعنيش أن العسل فاسد.',image:'https://images.unsplash.com/photo-1499195333224-3ce974eecb47?auto=format&fit=crop&w=900&q=80',createdAt:Date.now()-86400000}];
function waLink(product){const phone=(settings.whatsapp||'').replace(/\D/g,'');const msg=product?`السلام عليكم، بغيت نطلب:\n🍯 ${product.name}\n⚖️ ${product.weight||''}\n💰 ${product.price} درهم\n📍 التوصيل فالقنيطرة. واش متوفر؟`:`السلام عليكم، بغيت نسول على منتجات العسل والتوصيل فالقنيطرة.`;return `https://wa.me/${phone}?text=${encodeURIComponent(msg)}`}
function renderSettings(){document.querySelectorAll('#brandName,#footerName').forEach(e=>e.textContent=settings.shopName||'عسل القنيطرة');document.getElementById('heroText').textContent=settings.heroText||'';const generic=waLink();['heroWhatsApp','ctaWhatsApp'].forEach(id=>{document.getElementById(id).href=generic;document.getElementById(id).target='_blank'});document.getElementById('footerPhone').textContent=settings.whatsapp?`واتساب: +${settings.whatsapp.replace(/\D/g,'')}`:''}
function renderProducts(data){const arr=Object.entries(data||{}).map(([id,v])=>({id,...v})).filter(x=>x.active!==false);const items=arr.length?arr:fallbackProducts;document.getElementById('productsGrid').innerHTML=items.map(p=>`<article class="product-card"><div class="product-image"><img loading="lazy" src="${esc(p.image||'')}" alt="${esc(p.name)}"><span class="badge">${esc(p.badge||'عسل طبيعي')}</span></div><div class="product-body"><h3 class="product-name">${esc(p.name)}</h3><p class="product-desc">${esc(p.description||'')}</p><div class="product-meta"><div><span class="price">${Number(p.price||0).toFixed(0)} درهم</span>${p.oldPrice?`<span class="old-price">${Number(p.oldPrice).toFixed(0)} درهم</span>`:''}</div><span class="weight">${esc(p.weight||'')}</span></div><div class="product-actions"><a class="btn wa-btn" target="_blank" rel="noopener" href="${waLink(p)}">💬 اطلب عبر واتساب</a><button class="btn btn-soft" onclick='navigator.clipboard?.writeText(${JSON.stringify(p.name)})'>نسخ</button></div></div></article>`).join('')}
function renderArticles(data){const arr=Object.entries(data||{}).map(([id,v])=>({id,...v})).filter(x=>x.active!==false).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));const items=arr.length?arr:fallbackArticles;articlesCache=Object.fromEntries(items.map(a=>[a.id,a]));document.getElementById('articlesGrid').innerHTML=items.map(a=>`<article class="article-card"><div class="article-image"><img loading="lazy" src="${esc(a.image||'')}" alt="${esc(a.title)}"></div><div class="article-body"><span class="article-date">${fmtDate(a.createdAt)}</span><h3>${esc(a.title)}</h3><p>${esc(a.excerpt||'')}</p><button class="btn btn-outline" onclick="openArticle('${a.id}')">اقرأ المقال</button></div></article>`).join('')}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function fmtDate(t){try{return new Intl.DateTimeFormat('ar-MA',{dateStyle:'medium'}).format(new Date(t||Date.now()))}catch{return ''}}
window.openArticle=id=>{const a=articlesCache[id];if(!a)return;document.getElementById('modalTitle').textContent=a.title;document.getElementById('modalContent').textContent=a.content||a.excerpt||'';document.getElementById('articleModal').classList.add('show')};window.closeArticle=()=>document.getElementById('articleModal').classList.remove('show');document.getElementById('articleModal').addEventListener('click',e=>{if(e.target.id==='articleModal')closeArticle()});document.getElementById('year').textContent=new Date().getFullYear();
onValue(ref(db,`${root}/settings`),s=>{if(s.exists())settings={...settings,...s.val()};renderSettings()});onValue(ref(db,`${root}/products`),s=>renderProducts(s.val()));onValue(ref(db,`${root}/articles`),s=>renderArticles(s.val()));
