import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getDatabase, ref, set, get, update, push, onValue, onChildAdded, onDisconnect, remove, query, orderByChild, equalTo, limitToFirst } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";

const firebaseConfig={apiKey:"AIzaSyA8YL70CSgDJ8CdPT1Q8doAiy-8jYoyxe0",authDomain:"bi9agame.firebaseapp.com",databaseURL:"https://bi9agame-default-rtdb.firebaseio.com",projectId:"bi9agame",storageBucket:"bi9agame.firebasestorage.app",messagingSenderId:"959072355800",appId:"1:959072355800:web:e551182bc78cf5b6d61ead",measurementId:"G-CW0C4XR66N"};
const app=initializeApp(firebaseConfig),db=getDatabase(app),$=id=>document.getElementById(id);
const defaultWords={en:["apple","house","car","banana","cat","dog","tree","sun","moon","phone","pizza","guitar","chair","fish","airplane","book","flower","clock","glasses","key","horse","mountain","beach","robot","camera","football","rainbow","spoon","castle","train","burger","rocket","snake","computer","pencil","snowman","bridge","crown","ghost","island"],ar:["تفاحة","منزل","سيارة","موزة","قطة","كلب","شجرة","شمس","قمر","هاتف","بيتزا","قيثارة","كرسي","سمكة","طائرة","كتاب","وردة","ساعة","نظارة","مفتاح","حصان","جبل","بحر","روبوت","كاميرا","كرة","قوس قزح","ملعقة","قلعة","قطار","صاروخ","ثعبان","حاسوب","قلم","رجل ثلج","جسر","تاج","شبح","جزيرة"],fr:["pomme","maison","voiture","banane","chat","chien","arbre","soleil","lune","téléphone","pizza","guitare","chaise","poisson","avion","livre","fleur","horloge","lunettes","clé","cheval","montagne","plage","robot","caméra","football","arc-en-ciel","cuillère","château","train","fusée","serpent","ordinateur","crayon"]};
const palette=["#ffffff","#c1c1c1","#7d7d7d","#000000","#ff3b30","#ff9500","#ffcc00","#34c759","#00c7be","#32ade6","#007aff","#5856d6","#af52de","#ff2d55"];
let roomId="",playerId=crypto.randomUUID(),playerName="",roomState=null,unsubs=[],drawing=false,last=null,activePointerId=null,brushColor="#000000",brushSize=9,tool="brush",timerInt=null,avatarSeed=Math.floor(Math.random()*8),avatarData={mode:"parts",seed:avatarSeed,skin:"#f1c27d",hair:"#5b3927",eyes:"dot",mouth:"smile",drawing:""},strokeHistory=[],localStroke=[],lastRoundKey="",roundEnding=false,resultTimer=null;
const board=$("board"),ctx=board.getContext("2d",{willReadFrequently:true});

function toast(t){const e=$("toast");e.textContent=t;e.classList.add("show");clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove("show"),2400)}
function escapeHtml(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function cleanName(v){return String(v||"").trim().replace(/[<>]/g,"").slice(0,18)}
function normalize(v){return String(v||"").trim().toLocaleLowerCase().replace(/[أإآ]/g,"ا").replace(/ة/g,"ه").replace(/ى/g,"ي").replace(/[.,!?؟]/g,"")}
function makeCode(){const c="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:6},()=>c[Math.floor(Math.random()*c.length)]).join("")}
function rr(path=""){return ref(db,`rooms/${roomId}${path?"/"+path:""}`)}
function clearCanvas(){ctx.fillStyle="#fff";ctx.fillRect(0,0,board.width,board.height)}
clearCanvas();

function avatarHtml(p,cls="mini-avatar"){const a=p?.avatarData||{mode:"parts",seed:p?.avatar||0};if(a.mode==="draw"&&a.drawing)return `<div class="${cls}" style="background-image:url('${a.drawing}');background-size:cover;background-position:center"></div>`;const colors=["#5b3927","#111827","#b06b3c","#e2b13c","#753c77","#2563eb","#0f766e","#9b2c2c"],hair=a.hair||colors[(a.seed||0)%colors.length],skin=a.skin||"#f1c27d";return `<div class="${cls} avatar-render" style="--hair:${hair};--skin:${skin}"><i class="hair"></i><i class="eye e1 ${a.eyes||'dot'}"></i><i class="eye e2 ${a.eyes||'dot'}"></i><i class="mouth ${a.mouth||'smile'}"></i></div>`}
function paintAvatar(){avatarData.seed=avatarSeed;const el=$("avatarPreview"),colors=["#5b3927","#111827","#b06b3c","#e2b13c","#753c77","#2563eb","#0f766e","#9b2c2c"];avatarData.hair=avatarData.hair||colors[avatarSeed%colors.length];el.style.setProperty("--hair",avatarData.hair);el.style.setProperty("--skin",avatarData.skin);el.querySelector(".hair").style.background=avatarData.hair;if(avatarData.mode==="draw"&&avatarData.drawing){el.innerHTML="";el.style.background=`url('${avatarData.drawing}') center/cover`;el.style.borderRadius="50%"}else{el.style.background="";if(!el.querySelector('.hair'))el.innerHTML='<i class="hair"></i><i class="eye e1"></i><i class="eye e2"></i><i class="mouth"></i>'}}
paintAvatar();
$("randomAvatar").onclick=()=>{avatarSeed=(avatarSeed+1+Math.floor(Math.random()*7))%8;avatarData={...avatarData,mode:"parts",seed:avatarSeed,hair:["#5b3927","#111827","#b06b3c","#e2b13c","#753c77","#2563eb","#0f766e","#9b2c2c"][avatarSeed%8],drawing:""};paintAvatar()};
async function createRoom(isPublic=false){playerName=cleanName($("playerName").value);if(!playerName)return toast("Enter your name first");roomId=makeCode();const now=Date.now(),lang=$("language").value;await set(rr(),{createdAt:now,hostId:playerId,isPublic,status:"lobby",language:lang,maxPlayers:isPublic?8:8,drawTime:80,maxRounds:3,hints:2,currentRound:0,turnIndex:-1,drawerId:"",word:"",choices:[],roundEndsAt:0,players:{[playerId]:{name:playerName,score:0,joinedAt:now,guessed:false,avatar:avatarSeed,avatarData}}});enterRoom()}
async function quickPlay(){playerName=cleanName($("playerName").value);if(!playerName)return toast("Enter your name first");const q=query(ref(db,"rooms"),orderByChild("status"),equalTo("lobby"),limitToFirst(12));const snap=await get(q);let found=null;if(snap.exists()){for(const [id,r] of Object.entries(snap.val())){if(r.isPublic&&Object.keys(r.players||{}).length<(r.maxPlayers||8)){found=id;break}}}if(found){$("roomCode").value=found;await joinRoom(found)}else await createRoom(true)}
async function joinRoom(forced){playerName=cleanName($("playerName").value);if(!playerName)return toast("Enter your name first");roomId=String(forced||$("roomCode").value).trim().toUpperCase();if(roomId.length!==6)return toast("Invalid room code");const s=await get(rr());if(!s.exists())return toast("Room not found");const r=s.val();if(Object.keys(r.players||{}).length>=(r.maxPlayers||8))return toast("Room is full");await set(rr(`players/${playerId}`),{name:playerName,score:0,joinedAt:Date.now(),guessed:false,avatar:avatarSeed,avatarData});enterRoom()}
function enterRoom(){history.replaceState(null,"",`${location.pathname}?room=${roomId}`);$("home").classList.add("hidden");$("room").classList.remove("hidden");$("roomCodeBig").textContent=roomId;onDisconnect(rr(`players/${playerId}`)).remove();subscribe()}
function subscribe(){unsubs.push(onValue(rr(),s=>{if(!s.exists()){toast("Room closed");return leaveLocal()}roomState=s.val();render()}));unsubs.push(onChildAdded(rr("strokes"),s=>applyStroke(s.val())));unsubs.push(onChildAdded(rr("chat"),s=>addChat(s.val())))}

function sortedPlayers(){return Object.entries(roomState?.players||{}).sort((a,b)=>(a[1].joinedAt||0)-(b[1].joinedAt||0))}
function render(){const players=sortedPlayers(),isHost=roomState.hostId===playerId,isCurrentDrawer=roomState.drawerId===playerId,isDrawer=isCurrentDrawer&&roomState.status==="playing";$("playersList").innerHTML=players.map(([id,p],idx)=>`<div class="player-row ${id===playerId?"me":""} ${id===roomState.drawerId?"drawer":""} ${p.guessed?"guessed":""}">${avatarHtml(p)}<div class="player-meta"><div class="player-name">#${idx+1} ${escapeHtml(p.name)}${id===roomState.hostId?' 👑':''}</div><div class="player-state">${id===roomState.drawerId?'drawing':p.guessed?'guessed!':'playing'}</div></div><div class="player-score">${p.score||0}</div></div>`).join("");
  $("lobbyOverlay").classList.toggle("hidden",roomState.status!=="lobby");$("hostSettings").classList.toggle("hidden",!isHost);$("customWords").classList.toggle("hidden",!isHost);$("customOnly").parentElement.classList.toggle("hidden",!isHost);$("startGame").classList.toggle("hidden",!isHost);$("toolbar").classList.toggle("disabled",!isDrawer);$("spectatorNote").classList.toggle("hidden",isDrawer||roomState.status!=="playing");
  if(roomState.status==="lobby"){$("roundText").textContent="Waiting room";$("wordDisplay").textContent="_ _ _ _";stopTimer();syncSettingsUI()}
  if(roomState.status==="choosing"){$("roundText").textContent=`Round ${roomState.currentRound} of ${roomState.maxRounds}`;$("wordDisplay").textContent=isDrawer?"Choose a word":"Choosing a word...";$("chooseOverlay").classList.toggle("hidden",!isCurrentDrawer);if(isCurrentDrawer)renderChoices();stopTimer()}
  else $("chooseOverlay").classList.add("hidden");
  if(roomState.status==="playing"){$("roundText").textContent=`Round ${roomState.currentRound} of ${roomState.maxRounds}`;$("wordDisplay").textContent=isDrawer?roomState.word:maskedWord();startTimer();const key=`${roomState.currentRound}:${roomState.turnIndex}:${roomState.roundEndsAt}`;if(key!==lastRoundKey){lastRoundKey=key;strokeHistory=[];clearCanvas()}}
  if(roomState.status==="round_end"){stopTimer();$("roundText").textContent=`Round ${roomState.currentRound} result`;$("wordDisplay").textContent=roomState.word||"";showRoundResult()}
  else $("resultOverlay").classList.add("hidden");
  if(roomState.status==="finished"){$("roundText").textContent="Game finished";$("wordDisplay").textContent="🏆";stopTimer();showFinalResults(isHost)}else $("finalOverlay").classList.add("hidden")
}
function syncSettingsUI(){if(roomState.hostId!==playerId)return;$("setPlayers").value=String(roomState.maxPlayers||8);$("setTime").value=String(roomState.drawTime||80);$("setRounds").value=String(roomState.maxRounds||3);$("setHints").value=String(roomState.hints??2)}
function maskedWord(){const w=roomState.word||"",total=roomState.drawTime||80,left=Math.max(0,Math.ceil((roomState.roundEndsAt-Date.now())/1000)),elapsed=total-left,hints=Math.min(roomState.hints||0,Math.floor(elapsed/(total/((roomState.hints||0)+1))));const letters=[...w];let reveal=new Set();for(let n=0;n<hints;n++){const candidates=letters.map((c,i)=>c!==" "&&!reveal.has(i)?i:-1).filter(i=>i>=0);if(candidates.length)reveal.add(candidates[(n*7+roomState.currentRound+roomState.turnIndex)%candidates.length])}return letters.map((c,i)=>c===" "?"   ":reveal.has(i)?c:"_").join(" ")}
function renderChoices(){$("wordChoices").innerHTML=(roomState.choices||[]).map(w=>`<button class="word-choice" data-word="${escapeHtml(w)}">${escapeHtml(w)}</button>`).join("");document.querySelectorAll(".word-choice").forEach(b=>b.onclick=()=>chooseWord(b.dataset.word))}

function collectWords(){const lang=roomState.language||"en",custom=$("customWords").value.split(",").map(x=>x.trim()).filter(x=>x.length>1&&x.length<33),base=defaultWords[lang]||defaultWords.en;return $("customOnly").checked&&custom.length>=3?custom:[...base,...custom]}
function pickN(arr,n){const a=[...new Set(arr)].sort(()=>Math.random()-.5);return a.slice(0,n)}
async function saveSettings(){if(roomState?.hostId!==playerId)return;await update(rr(),{maxPlayers:+$("setPlayers").value,drawTime:+$("setTime").value,maxRounds:+$("setRounds").value,hints:+$("setHints").value,customWords:$("customWords").value,customOnly:$("customOnly").checked})}
async function startGame(){if(roomState.hostId!==playerId)return;await saveSettings();const count=Object.keys(roomState.players||{}).length;if(count<2)return toast("Need at least 2 players");await remove(rr("chat"));await remove(rr("strokes"));const scores={};for(const id of Object.keys(roomState.players))scores[`players/${id}/score`]=0;await update(rr(),scores);await startTurn(1,0)}
async function startTurn(round,index){roundEnding=false;const ids=sortedPlayers().map(x=>x[0]);if(!ids.length)return;if(index>=ids.length){round++;index=0}if(round>(roomState.maxRounds||3)){await update(rr(),{status:"finished",drawerId:"",word:"",roundEndsAt:0,finishedAt:Date.now()});return}const words=(roomState.customOnly&&roomState.customWords)?roomState.customWords.split(",").map(x=>x.trim()).filter(Boolean):[...(defaultWords[roomState.language]||defaultWords.en),...String(roomState.customWords||"").split(",").map(x=>x.trim()).filter(Boolean)];const choices=pickN(words,3);const reset={};for(const id of ids)reset[`players/${id}/guessed`]=false;await update(rr(),{status:"choosing",currentRound:round,turnIndex:index,drawerId:ids[index],choices,word:"",roundEndsAt:0,roundResult:null,...reset});await push(rr("strokes"),{type:"clear",at:Date.now()});await push(rr("chat"),{type:"system",text:`Round ${round}: ${roomState.players[ids[index]]?.name||'Player'} is choosing a word`,at:Date.now()});if(ids[index]===playerId)setTimeout(()=>{if(roomState?.status==="choosing"&&roomState?.drawerId===playerId&&roomState?.choices?.[0])chooseWord(roomState.choices[0])},12000)}
async function chooseWord(word){if(roomState.drawerId!==playerId||roomState.status!=="choosing")return;await update(rr(),{status:"playing",word,roundEndsAt:Date.now()+(roomState.drawTime||80)*1000,roundStartedAt:Date.now()});await push(rr("chat"),{type:"system",text:"Drawing started!",at:Date.now()})}
async function nextTurn(){if(roundEnding||roomState?.hostId!==playerId||roomState?.status!=="playing")return;roundEnding=true;const state=roomState,players=Object.entries(state.players||{}).sort((a,b)=>(b[1].score||0)-(a[1].score||0));const guessed=players.filter(([id,p])=>id!==state.drawerId&&p.guessed);const winner=guessed[0]||players[0]||["",{name:"No winner",score:0}];const result={winnerId:winner[0],winnerName:winner[1].name||"Player",winnerScore:winner[1].score||0,winnerAvatar:winner[1].avatarData||null,winnerSeed:winner[1].avatar||0,word:state.word,endsAt:Date.now()+4500,nextRound:state.currentRound,nextIndex:state.turnIndex+1};await update(rr(),{status:"round_end",roundEndsAt:0,roundResult:result});await push(rr("chat"),{type:"system",text:`The word was: ${state.word}`,at:Date.now()});setTimeout(async()=>{const fresh=await get(rr());if(!fresh.exists())return;const r=fresh.val();if(r.hostId===playerId&&r.status==="round_end"&&r.roundResult?.endsAt===result.endsAt)await startTurn(result.nextRound,result.nextIndex)},4600)}
function startTimer(){stopTimer();const tick=()=>{if(!roomState||roomState.status!=="playing")return;const left=Math.max(0,Math.ceil((roomState.roundEndsAt-Date.now())/1000));$("timer").textContent=left;$("wordDisplay").textContent=roomState.drawerId===playerId?roomState.word:maskedWord();if(left<=0&&roomState.hostId===playerId&&!roundEnding)nextTurn()};tick();timerInt=setInterval(tick,500)}
function stopTimer(){clearInterval(timerInt);timerInt=null;$("timer").textContent="--"}

function pos(e){const r=board.getBoundingClientRect();return{x:(e.clientX-r.left)*board.width/r.width,y:(e.clientY-r.top)*board.height/r.height}}
function line(s){ctx.strokeStyle=s.color;ctx.lineWidth=s.size;ctx.lineCap="round";ctx.lineJoin="round";ctx.beginPath();ctx.moveTo(s.x1,s.y1);ctx.lineTo(s.x2,s.y2);ctx.stroke()}
function applyStroke(s){if(!s)return;if(s.type==="clear"){clearCanvas();strokeHistory=[];return}if(s.type==="line"){line(s);strokeHistory.push(s)}if(s.type==="fill"){floodFill(Math.round(s.x),Math.round(s.y),s.color);strokeHistory.push(s)}if(s.type==="undo"){strokeHistory.pop();redrawHistory()}}
function redrawHistory(){clearCanvas();for(const s of strokeHistory){if(s.type==="line")line(s);else if(s.type==="fill")floodFill(Math.round(s.x),Math.round(s.y),s.color)}}
function hexToRgb(h){h=h.replace("#","");return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16),255]}
function floodFill(x,y,color){x=Math.max(0,Math.min(board.width-1,x));y=Math.max(0,Math.min(board.height-1,y));const img=ctx.getImageData(0,0,board.width,board.height),d=img.data,w=board.width,idx=(y*w+x)*4,target=[d[idx],d[idx+1],d[idx+2],d[idx+3]],rep=hexToRgb(color);if(target.every((v,i)=>v===rep[i]))return;const same=i=>d[i]===target[0]&&d[i+1]===target[1]&&d[i+2]===target[2]&&d[i+3]===target[3],stack=[[x,y]],seen=new Uint8Array(w*board.height);while(stack.length){const [cx,cy]=stack.pop(),pi=cy*w+cx;if(seen[pi])continue;seen[pi]=1;const i=pi*4;if(!same(i))continue;d[i]=rep[0];d[i+1]=rep[1];d[i+2]=rep[2];d[i+3]=255;if(cx>0)stack.push([cx-1,cy]);if(cx<w-1)stack.push([cx+1,cy]);if(cy>0)stack.push([cx,cy-1]);if(cy<board.height-1)stack.push([cx,cy+1])}ctx.putImageData(img,0,0)}
board.addEventListener("pointerdown",async e=>{if(roomState?.drawerId!==playerId||roomState?.status!=="playing")return;e.preventDefault();const p=pos(e);if(tool==="fill"){await push(rr("strokes"),{type:"fill",x:p.x,y:p.y,color:brushColor,at:Date.now()});return}drawing=true;activePointerId=e.pointerId;last=p;localStroke=[];try{board.setPointerCapture(e.pointerId)}catch{}});
board.addEventListener("pointermove",e=>{if(!drawing||!last||e.pointerId!==activePointerId)return;e.preventDefault();const p=pos(e),s={type:"line",x1:last.x,y1:last.y,x2:p.x,y2:p.y,color:tool==="eraser"?"#ffffff":brushColor,size:tool==="eraser"?Math.max(18,brushSize*2):brushSize,at:Date.now()};line(s);localStroke.push(s);last=p});
async function endBoardStroke(e,commit=true){if(!drawing)return;if(e&&activePointerId!==null&&e.pointerId!==undefined&&e.pointerId!==activePointerId)return;const batch=localStroke.slice();drawing=false;last=null;activePointerId=null;localStroke=[];if(commit&&roomState?.status==="playing"&&roomState?.drawerId===playerId){for(const stroke of batch)await push(rr("strokes"),stroke)}}
board.addEventListener("pointerup",e=>endBoardStroke(e,true));board.addEventListener("pointercancel",e=>endBoardStroke(e,false));board.addEventListener("lostpointercapture",e=>endBoardStroke(e,true));window.addEventListener("pointerup",e=>endBoardStroke(e,true));window.addEventListener("blur",()=>endBoardStroke(null,true));document.addEventListener("visibilitychange",()=>{if(document.hidden)endBoardStroke(null,true)});

function initToolbar(){const p=$("palette");p.innerHTML=palette.map(c=>`<button class="color-swatch ${c==="#000000"?"active":""}" data-color="${c}" style="background:${c}"></button>`).join("");document.querySelectorAll(".color-swatch").forEach(b=>b.onclick=()=>{document.querySelectorAll(".color-swatch").forEach(x=>x.classList.remove("active"));b.classList.add("active");brushColor=b.dataset.color;tool="brush";selectTool()});document.querySelectorAll(".tool").forEach(b=>b.onclick=()=>{tool=b.dataset.tool;selectTool()});document.querySelectorAll(".sizes button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".sizes button").forEach(x=>x.classList.remove("active"));b.classList.add("active");brushSize=+b.dataset.size})}
function selectTool(){document.querySelectorAll(".tool").forEach(x=>x.classList.toggle("active",x.dataset.tool===tool))}
initToolbar();
$("undoBtn").onclick=async()=>{if(roomState?.drawerId===playerId)await push(rr("strokes"),{type:"undo",at:Date.now()})};$("clearBtn").onclick=async()=>{if(roomState?.drawerId===playerId)await push(rr("strokes"),{type:"clear",at:Date.now()})};

$("chatForm").addEventListener("submit",async e=>{e.preventDefault();const inp=$("chatInput"),text=inp.value.trim();if(!text||!roomState)return;inp.value="";const me=roomState.players?.[playerId];if(roomState.status==="playing"&&playerId!==roomState.drawerId&&!me?.guessed){const guess=normalize(text),answer=normalize(roomState.word);if(guess===answer){const left=Math.max(0,Math.ceil((roomState.roundEndsAt-Date.now())/1000)),gain=Math.round(100+left*4);await update(rr(),{[`players/${playerId}/score`]:(me.score||0)+gain,[`players/${playerId}/guessed`]:true,[`players/${roomState.drawerId}/score`]:(roomState.players[roomState.drawerId]?.score||0)+50});await push(rr("chat"),{type:"correct",name:playerName,text:"guessed the word!",at:Date.now()});const others=Object.entries(roomState.players).filter(([id,p])=>id!==roomState.drawerId&&id!==playerId&&!p.guessed);if(!others.length&&roomState.hostId===playerId)setTimeout(nextTurn,800);return}if(answer.startsWith(guess)&&guess.length>=Math.max(3,answer.length-2)){await push(rr("chat"),{type:"close",name:playerName,text:"is close!",at:Date.now()});return}}await push(rr("chat"),{type:"chat",name:playerName,text:text.slice(0,90),at:Date.now()})});
function addChat(m){const d=document.createElement("div");d.className=`chat-line ${m.type||"chat"}`;if(m.type==="system")d.textContent=m.text;else if(m.type==="correct")d.textContent=`${m.name} ${m.text}`;else if(m.type==="close")d.textContent=`${m.name} ${m.text}`;else d.innerHTML=`<b>${escapeHtml(m.name)}:</b> ${escapeHtml(m.text)}`;$("chatMessages").appendChild(d);$("chatMessages").scrollTop=$("chatMessages").scrollHeight}

function renderAvatarInto(el,p){el.innerHTML="";el.style.backgroundImage="";const a=p?.avatarData||p?.winnerAvatar||null;if(a?.mode==="draw"&&a.drawing){el.style.backgroundImage=`url('${a.drawing}')`;return}const seed=p?.avatar??p?.winnerSeed??a?.seed??0;el.innerHTML=avatarHtml({avatar:seed,avatarData:a},"result-inline-avatar")}
function showRoundResult(){const r=roomState.roundResult;if(!r)return;$("resultOverlay").classList.remove("hidden");$("resultName").textContent=r.winnerName||"Player";$("resultScore").textContent=`${r.winnerScore||0} total points`;$("resultWord").textContent=`The word was: ${r.word||roomState.word||''}`;renderAvatarInto($("resultAvatar"),{avatarData:r.winnerAvatar,avatar:r.winnerSeed});const sec=Math.max(0,Math.ceil(((r.endsAt||Date.now())-Date.now())/1000));$("resultCountdown").textContent=`Next round in ${sec}`;clearTimeout(resultTimer);resultTimer=setTimeout(()=>{if(roomState?.status==="round_end")showRoundResult()},500)}
function showFinalResults(isHost){$("finalOverlay").classList.remove("hidden");const top=Object.entries(roomState.players||{}).sort((a,b)=>(b[1].score||0)-(a[1].score||0)).slice(0,3);$("podium").innerHTML=top.map(([id,p],i)=>`<div class="podium-place ${i===0?'first':i===1?'second':'third'}"><div class="podium-rank">${['🥇','🥈','🥉'][i]}</div>${avatarHtml(p,'podium-avatar')}<div>${escapeHtml(p.name)}</div><strong>${p.score||0}</strong></div>`).join("");$("backLobby").classList.toggle("hidden",!isHost)}
$("backLobby").onclick=async()=>{if(roomState?.hostId!==playerId)return;await update(rr(),{status:"lobby",currentRound:0,turnIndex:-1,drawerId:"",word:"",roundEndsAt:0,roundResult:null});};

// Avatar maker
const faceCanvas=$("faceCanvas"),faceCtx=faceCanvas.getContext("2d");let faceDrawing=false,faceErase=false,faceLast=null;function resetFaceCanvas(){faceCtx.fillStyle="#fff";faceCtx.fillRect(0,0,256,256)}resetFaceCanvas();
function syncMakerPreview(){const m=$("makerPreview");m.style.setProperty("--skin",$("skinColor").value);m.style.setProperty("--hair",$("hairColor").value);m.querySelectorAll('.eye').forEach(x=>x.className=x.className.replace(/ happy| wide| dot/g,'')+' '+$("eyeStyle").value);const mouth=m.querySelector('.mouth');mouth.className='mouth '+$("mouthStyle").value}
$("customizeAvatar").onclick=()=>{$("avatarMaker").classList.remove("hidden");syncMakerPreview()};$("closeAvatarMaker").onclick=()=>$("avatarMaker").classList.add("hidden");document.querySelectorAll('.avatar-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.avatar-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$("partsMaker").classList.toggle('hidden',b.dataset.mode!=="parts");$("drawMaker").classList.toggle('hidden',b.dataset.mode!=="draw")});["skinColor","hairColor","eyeStyle","mouthStyle"].forEach(id=>$(id).addEventListener('input',syncMakerPreview));
function facePos(e){const r=faceCanvas.getBoundingClientRect();return{x:(e.clientX-r.left)*256/r.width,y:(e.clientY-r.top)*256/r.height}}faceCanvas.addEventListener('pointerdown',e=>{faceDrawing=true;faceLast=facePos(e);try{faceCanvas.setPointerCapture(e.pointerId)}catch{}});faceCanvas.addEventListener('pointermove',e=>{if(!faceDrawing)return;const p=facePos(e);faceCtx.strokeStyle=faceErase?'#fff':$("faceColor").value;faceCtx.lineWidth=+$("faceSize").value;faceCtx.lineCap='round';faceCtx.beginPath();faceCtx.moveTo(faceLast.x,faceLast.y);faceCtx.lineTo(p.x,p.y);faceCtx.stroke();faceLast=p});const endFace=()=>{faceDrawing=false;faceLast=null};faceCanvas.addEventListener('pointerup',endFace);faceCanvas.addEventListener('pointercancel',endFace);faceCanvas.addEventListener('lostpointercapture',endFace);$("faceErase").onclick=()=>{faceErase=!faceErase;$("faceErase").classList.toggle('active',faceErase)};$("faceClear").onclick=resetFaceCanvas;$("saveAvatar").onclick=()=>{const mode=document.querySelector('.avatar-tab.active')?.dataset.mode||'parts';if(mode==='draw'){avatarData={mode:'draw',drawing:faceCanvas.toDataURL('image/webp',.55),seed:avatarSeed}}else avatarData={mode:'parts',seed:avatarSeed,skin:$("skinColor").value,hair:$("hairColor").value,eyes:$("eyeStyle").value,mouth:$("mouthStyle").value,drawing:''};$("avatarMaker").classList.add('hidden');paintAvatar();toast('Avatar saved!')};

async function leaveRoom(){try{await remove(rr(`players/${playerId}`));if(roomState?.hostId===playerId){const ids=sortedPlayers().map(x=>x[0]).filter(id=>id!==playerId);if(ids.length)await update(rr(),{hostId:ids[0]});else await remove(rr())}}catch{}leaveLocal()}
function leaveLocal(){for(const u of unsubs)try{u()}catch{}unsubs=[];stopTimer();roomId="";roomState=null;lastRoundKey="";history.replaceState(null,"",location.pathname);$("room").classList.add("hidden");$("home").classList.remove("hidden");clearCanvas()}

$("quickPlay").onclick=()=>quickPlay().catch(e=>toast("Firebase: "+e.message));
$("createPrivate").onclick=()=>createRoom(false).catch(e=>toast("Firebase: "+e.message));
$("joinRoom").onclick=()=>joinRoom().catch(e=>toast("Firebase: "+e.message));
$("startGame").onclick=()=>startGame().catch(e=>toast(e.message));
$("leaveRoom").onclick=leaveRoom;
$("copyInvite").onclick=async()=>{const url=`${location.origin}${location.pathname}?room=${roomId}`;try{await navigator.clipboard.writeText(url);toast("Invite link copied!")}catch{toast(url)}};
for(const id of ["setPlayers","setTime","setRounds","setHints"])$(id).addEventListener("change",()=>saveSettings().catch(()=>{}));
$("customWords").addEventListener("change",()=>saveSettings().catch(()=>{}));
$("customOnly").addEventListener("change",()=>saveSettings().catch(()=>{}));
window.addEventListener("beforeunload",()=>{if(roomId)remove(rr(`players/${playerId}`)).catch(()=>{})});
const initialRoom=new URLSearchParams(location.search).get("room");if(initialRoom){$("roomCode").value=initialRoom.toUpperCase().slice(0,6);toast("Enter your name, then Join")}
